### PR TITLE
UserSettings to define Locale

### PR DESCRIPTION
**Pull request by joaoantunes87**

### CODE REVIEW

**Comment by jason-p-pickering** [comment]
@joaoantunes87 Its still not exactly clear what is happening with this PR, since the dependencies have been updated. Are these changes relevant/required for this particular issue?

**Comment by joaoantunes87** [comment]
I am not understanding what is the real problem. Without this PR the language will be the one defined by the browser and not user settings at dhis2.

**Comment by jason-p-pickering** [comment]
@joaoantunes87 I do not understand why you have modified the package-lock.json and yarn.lock in this particular PR?

**Comment by joaoantunes87** [comment]
The library "i18next-browser-languagedetector" was removed, so I executed "npm install" and "yarn install" to make sure all the dependencies were updated.

**Comment by joaoantunes87** [comment]
@jason-p-pickering I have removed package-lock.json, yarn.lock locally and generating it from scratch. Just give me a minute to see if it will get a different version.

**Comment by joaoantunes87** [comment]
I have updated it. Could you see if it is ok now, please?

**Comment by jason-p-pickering** [comment]
Changes in lock files were due to removal of a dependency.

**Pull request merged**
